version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: drfmsgdb
      POSTGRES_USER: drfuser
      POSTGRES_PASSWORD: drfpass

volumes:
  postgres_data:
  static_volume:

