# Generated by Django 5.2.3 on 2025-06-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messagesapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Message",
                "verbose_name_plural": "02. Messages",
            },
        ),
    ]
